name: CI Dotnet

on:
    workflow_dispatch:
        inputs:
            dotnet-version:
                type: "string"
                description: "dotnet version"
                default: "8.x"
            path:
                type: "string"
                description:  "app path"
                default: "/"

jobs:
    build:
        runs-on: "ubuntu-latest"
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v3"

            - name: "Setup .NET"
              uses: "actions/setup-dotnet@v3"
              with:
                dotnet-version: ${{ github.event.inputs.dotnet-version }}
            
            - name: "Set dependencies"
              uses: "actions/cache@v3"
              with:
                path: ~/.nuget/packages
                key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
                restore-keys: |
                    ${{ runner.os }}-nuget-

            - name: "Build"
              run: dotnet build WebApplication1.sln --configuration Release --no-restore 
        
            - name: "SonarQube scanTest"
              run: sonarsource/sonarqube-scan-action@<action version>
              env: 
                SONAR_TOKEN: ${{ var.SONAR_TOKEN }}
                SONAR_HOST_URL: ${{ var.SONAR_HOST_URL }}


    
          
