name: CI Dotnet

on:
    workflow_dispatch:
        inputs:
            dotnet-version:
                type: "string"
                description: "dotnet version"
                default: "8.x"
            path:
                type: "string"
                description:  "app path"
                default: "/"

jobs:
    build:
        runs-on: "ubuntu-latest"
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v3"

            - name: "Setup .NET"
              uses: "actions/setup-dotnet@v3"
              with:
                dotnet-version: ${{ github.event.inputs.dotnet-version }}
            
            # - name: "Set dependencies"
            #   uses: "actions/cache@v3"
            #   with:
            #     path: ~/.nuget/packages
            #     key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
            #     restore-keys: |
            #         ${{ runner.os }}-nuget-

            - name: "Restore dependencies"
              run: dotnet restore          

            - name: "Build"
              run: dotnet build WebApplication1.sln --configuration Release --no-restore 
        
            - name: SonarQube Scan
              uses: kitabisa/sonarqube-action@v1.2.0
              with:
                host: ${{ vars.SONARQUBE_HOST }}
                login: ${{ secrets.SONARQUBE_TOKEN }}

            - name: Publish
              run: dotnet publish WebApplication1.sln --configuration Release --output ./webapp
    
            - name: Archive build artifacts
              uses: actions/upload-artifact@v4
              with: 
                name: dotnet-app
                path: ./webapp